nama_wilayah=input("Masukkan nama wilayah: ")
kemacetan=int(input("Masukkan tingkat kemacetan(%): "))
sampah=int(input("Masukkan tingkat sampah(%): "))
lampu_mati=int(input("Masukkan jumlah lampu mati: "))
print("===========Data wilayah ==========")
print(f"Nama wilayah: {nama_wilayah}")
print(f"Tingkat kemacetan: {kemacetan}%")
print(f"Tingkat sampah: {sampah}%")
print(f"Jumlah lampu mati: {lampu_mati}")
