nama=(input("Masukkan nama: "))  
umur = int(input("Masukkan umur: "))
hobi = (input("Masukkan hobi: "))
tahun_lahir = int(input("Masukkan tahun lahir: "))
umur = 2026 - tahun_lahir
makanan_favorit = (input("Masukkan makanan favorit: "))
print("===========Biodata ==========")
print(f"halo nama saya,{nama}")
print(f"saya berumur {umur} tahun")
print(f"Hobi saya {hobi}")
print(f"Makanan Favorit saya {makanan_favorit}")
